[package]
name = "sudoku"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
trees = {git = "https://github.com/YvDem/rust_tree_impl"  }
